system_groups:
  - { name: slurm, gid: 1025 }

system_users:
  - {
      name: slurm,
      uid: 1025,
      group: slurm,
      shell: /sbin/nologin,
      create_home: no,
      group_names: ["galaxyserver", "slurm"],
    }
  - {
      name: brugger,
      uid: 1026,
      group: users,
      shell: /bin/bash,
      create_home: yes,
      group_names: ["wheel"],
    }


munge_key: 15dd2f4e7cb41a49b065db2341e7342f


mysql_databases: 
  - name: slurm_acct
  - name: cromwell
mysql_users: 
  - name: slurm
    host: "localhost"
    password: slurm
    priv: "slurm_acct.*:ALL"
  - name: cromwell
    host: localhost
    password: cromwell
    priv: "cromwell.*:ALL"


ecc_root: /cluster/software/ecc
ecc_user: sysadmin

ecc_playbook_root: /cluster/software/ecc-playbook