# this is needed otherwise not all information will be available for creating the slurm config for the controller.
- hosts: all
  become: true

  vars_files:
    group_vars/system.yml


  tasks:
    - name: Install packages
      include: tasks/base_system.yml
      tags: 'base'
    - name: Create users and groups
      include: tasks/users_groups.yml
      tags: 'users'

- hosts: ecc-head
  become: true

  vars_files:
    group_vars/system.yml

  tasks:
    - name: install slurm head
      include: tasks/slurm_head.yml
      tags: 'slurm'

    - name: setup slurm
      include: tasks/slurm_general.yml
      tags: 'slurm'
