# this is needed otherwise not all information will be available for creating the slurm config for the controller.
- hosts: all
  become: true

  vars:
    group_vars/system.yml


  tasks:
    - name: enable epel
      package:
        name: epel-release

    - name: Install Dependencies
      package:
        name:
          - python3
          - git
          - jq
          - nfs-utils
          - vim 
          - libcgroup
          - libcgroup-tools
          - munge
          - nfs-utils
          - singularity

    - name: Create users and groups
      include: tasks/users_groups.yml
      tags: 'users'



