# this is needed otherwise not all information will be available for creating the slurm config for the controller.
- hosts: all
  gather_facts: yes

  tasks:
    - name: Install Dependencies
      package:
        name:
          - python3
          - git
          - jq
          - nfs-utils
          - vim libcgroup
          - libcgroup-tools
          - munge
          - nfs-utils
          - singularity

  roles:
    - role: geerlingguy.repo-epel


