# this is needed otherwise not all information will be available for creating the slurm config for the controller.
- hosts: all
  become: true

  vars_files:
    group_vars/system.yml

    - name: Create users and groups
      include: tasks/users_groups.yml
      tags: 'users'

    - name: restart slurm services
      include: tasks/slurm_restarts.yml
      tags: 'slurm-restart'
      