# this is needed otherwise not all information will be available for creating the slurm config for the controller.
- hosts: all
  become: true

  tags:
    - slurmconfig

  vars_files:
    group_vars/system.yml

  tasks:
    - name: Create users and groups
      include: tasks/users_groups.yml
      tags: 'users'
    - name: Update slurm config
      include: tasks/slurm_live.yml
      

- hosts: node
  become: true
  tags:
    - nodes

  tasks:
  - name: Mount data NFS volume
    ansible.posix.mount:
      src: userblobstoragekim.blob.core.windows.net:/userblobstoragekim/data
      path: /data
      opts: sec=sys,vers=3,nolock,proto=tcp
      state: mounted
      fstype: nfs
    when: False

  - name: Unmount data NFS volume
    ansible.posix.mount:
      path: /data
      state: unmounted
      fstype: nfs


  - name: Mount data NFS volume
    ansible.posix.mount:
      src: userstoragekim.file.core.windows.net:/userstoragekim/data
      path: /data
      opts: rw,vers=4,minorversion=1,sec=sys,sync
      state: mounted
      fstype: nfs
    when: True

  - name: Mount /usr/local/ NFS volume
    ansible.posix.mount:
      src: clusterresources.file.core.windows.net:/clusterresources/local
      path: /usr/local/
      opts: rw,vers=4,minorversion=1,sec=sys,sync
      state: mounted
      fstype: nfs

  - name: restart slurmd
    systemd:
      name: slurmd
      enabled: true
      state: restarted

- hosts: head
  become: true
  tags:
    - head
  tasks:
    - name: restart slurmctld
      systemd:
        name: slurmctld
        enabled: true
        state: restarted

