# this is needed otherwise not all information will be available for creating the slurm config for the controller.
- hosts: all
  become: true

  tags:
    - slurmconfig

  vars_files:
    group_vars/system.yml

  tasks:
    - name: Create users and groups
      include: tasks/users_groups.yml
      tags: 'users'

    - name: Update slurm config
      include: tasks/slurm_live.yml
      

- hosts: small, medium, large, huge
  become: true
  tags:
    - nodes

  include_tasks:
    file: tasks/live_cluster.yml


- hosts: head
  become: true
  tags:
    - head
  tasks:
    - name: restart slurmctld
      systemd:
        name: slurmctld
        enabled: true
        state: restarted

