# this is needed otherwise not all information will be available for creating the slurm config for the controller.
- hosts: all
  become: true

  vars_files:
    group_vars/system.yml

  tasks:
    - name: Create users and groups
      include: tasks/users_groups.yml
      tags: 'users'
    - name: Update slurm config
      include: tasks/slurm_live.yml
      

- hosts: head
  become: true
  tasks:
    - name: restart slurmctld
      systemd:
        name: slurmctld
        enabled: true
        state: restarted

- hosts: node
  become: true
  
  tasks:
  - name: Mount data NFS volume
    ansible.posix.mount:
      src: userstoragekim.file.core.windows.net:/userstoragekim/data
      path: /data
      opts: rw,vers=4,minorversion=1,sec=sys
      state: remounted
      fstype: nfs

  - name: Mount /usr/local/ NFS volume
    ansible.posix.mount:
      src: clusterresources.file.core.windows.net:/clusterresources/local
      path: /usr/local/
      opts: rw,vers=4,minorversion=1,sec=sys
      state: mounted
      fstype: nfs

    - name: restart slurmd
      systemd:
        name: slurmd
        enabled: true
        state: restarted
