# this is needed otherwise not all information will be available for creating the slurm config for the controller.
- hosts: all
  become: true

  vars_files:
    group_vars/system.yml

  tasks:
    - name: Create users and groups
      include: tasks/users_groups.yml
      tags: 'users'
      
- hosts: node
  become: true

  tasks:
    - name: copy slurm conf
      template: 
        src: files/slurm/slurm.conf
        dest: /etc/slurm/slurm.conf
        mode: 0644
        owner: slurm
        group: slurm
        backup: yes
    - name: restart slurmd
      systemd:
        name: slurmd
        enabled: true
        state: restarted
