# ansible module/roles (from ver > 2)
- src: posix

# Roles not from the Galaxy community
- src: geerlingguy.apache
  version: 3.1.0
- src: geerlingguy.ansible
  version: 2.0.2
- src: geerlingguy.git
  version: 3.0.0
- src: geerlingguy.java
  version: 1.10.0
- src: geerlingguy.pip
  version: 1.3.0
- src: geerlingguy.repo-epel
  version: 1.3.0
- src: geerlingguy.mysql
  version: 3.1.0
- src: geerlingguy.nfs
  version: 1.5.0
- src: weareinteractive.sudo
  version: 1.14.1

- src: https://github.com/dj-wasabi/ansible-telegraf
  name: dj-wasabi.telegraf
- src: idiv-biodiversity.postfix
  version: v0.4.0
- src: indigo-dc.nfs

