---
- name: enable epel
  package:
    name: epel-release

- name: Install Dependencies
  package:
    name:
      - python3
      - git
      - jq
      - nfs-utils
      - vim 
      - libcgroup
      - libcgroup-tools
      - munge
      - nfs-utils
      - singularity

- name: update pip
  pip: 
    name: pip
    executable: pip-3
    extra_args: --upgrade


- name: pip install wheel
  pip: 
    name: wheel
    executable: pip-3
    extra_args: --upgrade


- name: Add another bin dir to system-wide $PATH.
  copy:
    dest: /etc/profile.d/custom-path.sh
    content: 'PATH=$PATH:/cluster/bin/'

- name: update system
  yum:
    name: '*'
    state: latest

- name: nfs /cluster
  file:
    path: /cluster
    state: directory
    owner: root
    group: root

- name: nfs /data
  file:
    path: /data
    state: directory
    owner: root
    group: root

- name: add munge key
  copy:
    dest: "/etc/munge/munge.key"
    content: "{{munge_key}}"
    owner: munge
    group: munge
    mode: 0600

- name: ensure munge is running
  systemd:
    name: munge
    enabled: true
    state: started

- name: Mount data NFS volume
  ansible.posix.mount:
    src: kbrnfs.file.core.windows.net:/kbrnfs/cluster-data
    path: /data
    opts: rw,vers=4,minorversion=1,sec=sys
    state: mounted
    fstype: nfs

- name: Mount cluster NFS volume
  ansible.posix.mount:
    src: kbrnfs.file.core.windows.net:/kbrnfs/cluster
    path: /cluster
    opts: rw,vers=4,minorversion=1,sec=sys
    state: mounted
    fstype: nfs
