---
- name: enable epel
  package:
    name: epel-release

- name: Install Dependencies
  package:
    name:
      - python3
      - git
      - jq
      - nfs-utils
      - vim 
      - libcgroup
      - libcgroup-tools
      - munge
      - nfs-utils
      - singularity

- name: nfs /software
  file:
    path: /software
    state: directory
    owner: root
    group: root

- name: nfs /data
  file:
    path: /software
    state: directory
    owner: root
    group: root

- name: add munge key
  copy:
    dest: "/etc/munge/munge.key"
    content: "{{munge_key}}"
    owner: munge
    group: munge
    mode: 0600

- name: ensure munge is running
  systemd:
    name: munge
    enabled: true
    state: started
