
- name: Git checkout of ecc azure branch!
  git:
    repo: 'https://github.com/neuromics/ecc.git@azure'
    dest: "{{ ecc_root }}"

- name: create venv in {{ nels_galaxy_api_root }}
  command:
    chdir: "{{  ecc_root }}"
    cmd: python3 -m venv venv
    creates: "{{  ecc_root }}/venv"

- name: Install specified python requirements for ecc
  pip:
    requirements: "{{  ecc_root }}/requirements.txt"
    virtualenv: "{{  ecc_root }}/venv"


- name: check if ssh-key exists
  become: true
  become_user: "{{ecc_user}}"
  stat:
    path: $HOME/.ssh/id_rsa
  register: ssh_key

- name: create ssh key for connecting to nodes
  become: true
  become_user: "{{ecc_user}}"
  command: ssh-keygen -t rsa -f $HOME/.ssh/id_rsa -q -P ""
  when: ssh_key.stat.exists == false

- name: fetch created public ssh key
  become: true
  become_user: "{{ecc_user}}"
  shell: cat ~/.ssh/id_rsa.pub
  register: ssh_pub_key_cat

- name: store pub-key to be used later (seems off)
  set_fact:
    ssh_key: "{{ssh_pub_key_cat.stdout}}"

- name: Deploy ecc config file, will keep local copy if exists!
  template:
    src: templates/ecc/ecc.yam.j2
    dest: "{{ecc_root}/ecc.yaml"
    owner: "{{ecc_user}}"
    force: no



