---
- name: powertools!
  command: "dnf config-manager --enable PowerTools"

- name: install slurmctld and slurmdbd
  package:
    name:
      - slurm-slurmctld
      - slurm-slurmdbd
      - platform-python-devel
      - mariadb 
      - mariadb-server

