---
- name: powertools!
  dnf:
    name: "@PowerTools"
    state: present

- name: install slurmctld and slurmdbd
  package:
    name:
      - slurm-slurmctld
      - slurm-slurmdbd
      - platform-python-devel
      - mariadb 
      - mariadb-server

- name: slurm lib dir
  file:
    path: /var/lib/slurm/
    state: directory
    owner: slurm
    group: slurm

- name: slurm log
  file:
    path: /var/log/slurm
    state: directory
    owner: slurm
    group: slurm
