
- name: install cromwell-utils
  pip:
    name: git+https://www.github.com/neuromics/cromwell-utils.git
    extra_args: --prefix=/cluster/ 

- name: make dir for nsm-analysis
  file:
    path: "{{ nsm_analysis_root }}"
    owner: "{{nsm_analysis_user}}"
    state: directory

- name: Git checkout of nsm-analysis
  git:
    repo: https://github.com/neuromics/nsm-analysis.git
    dest: "{{ nsm_analysis_root }}"
    version: reorg
    force: yes

- name: ensure jar dir exists
  file:
    path: /cluster/jars/
    state: directory
    
- name: download cromwell-jar
  get_url: 
    url: https://github.com/broadinstitute/cromwell/releases/download/60/cromwell-60.jar
    dest: /cluster/jars/
    mode: '06440'

- name: download womtool-jar
  get_url: 
    url: https://github.com/broadinstitute/cromwell/releases/download/60/womtool-60.jar
    dest: /cluster/jars/
    mode: '06440'

- name: make imports paths absolute
  command: 
    chdir: "{{  nsm_analysis_root }}"
    cmd: /cluster/bin/cromwell-cli utils set-paths {{ nsm_analysis_root}}
